/**
 * Configuración global y constantes
 */

export const CATEGORY_MAP = {
    'TODO': '',
    'PLAZAS': 'CAT_PLAZAS',
    'EVENTOS': 'CAT_EVENTOS'
};

export const I18N = {
    es: {
        all: 'TODO', cat_plazas: 'PLAZAS', cat_eventos: 'EVENTOS',
        loading: 'Cargando ofertas VIP...', no_offers: 'No hay ofertas disponibles.',
        search_placeholder: 'Buscar agencias, modelos, ciudades...', contact_btn: 'VER CONTACTO',
        logout: 'CERRAR SESIÓN',
        nav_home: 'Inicio', nav_feed: 'Muro', nav_alerts: 'Alertas', nav_profile: 'Perfil',
        save_alerts: 'GUARDAR PREFERENCIAS', alerts_title: 'Configurar Alertas',
        select_language: 'SELECCIONAR IDIOMA', alert_monitoring_categories: '1. Categorías de Monitoreo',
        apply_btn: 'POSTULARSE', budget: 'PRESUPUESTO', discuss: 'A convenir',
        reveal_info: 'INFORMACIÓN REVELADA', open_wa: 'ABRIR WHATSAPP', open_tg: 'ABRIR TELEGRAM',
        profile_saved: '¡PERFIL GUARDADO! ✨', apply_sent: '¡POSTULACIÓN ENVIADA! ✨',
        fill_profile: 'Completa tu perfil antes de postularte.',
        wa_confirm: '¡Postulación enviada! ¿Quieres contactar ahora por WhatsApp?',
        acc_suspended: 'CUENTA SUSPENDIDAPOR INCUMPLIMIENTO.',
        no_contact: 'ESTE ANUNCIO NO DISPONE DE CONTACTO PÚBLICO.',
        saving: 'GUARDANDO...', save_profile: 'GUARDAR PERFIL ELITE',
        applying: 'ENVIANDO...', retry: 'REINTENTAR',
        tv: 'TV', tax: 'IMPUESTO', airbnb: 'AIRBNB', discount: 'DESCUENTO',
        // Landing
        verifying_session: 'VERIFICANDO SESIÓN',
        hero_badge: 'FEED EN VIVO FILTRADO POR IA',
        hero_title: 'La Red Global de<br><span class="gold-text italic">Inteligencia VIP</span>',
        hero_subtitle: 'Anuncios exclusivos en tiempo real de Telegram y WhatsApp, filtrados con precisión para miembros de Élite.',
        launch_app: 'ABRIR APP',
        account_access: 'ACCESO CUENTA',
        stat_cities: 'CIUDADES',
        stat_latency: 'LATENCIA'
    },
    en: {
        all: 'ALL', cat_plazas: 'POSITIONS', cat_eventos: 'EVENTS',
        loading: 'Loading live offers...', no_offers: 'No offers available.',
        search_placeholder: 'Search agencies, models...', contact_btn: 'VIEW CONTACT',
        logout: 'LOGOUT',
        nav_home: 'Home', nav_feed: 'Feed', nav_alerts: 'Alerts', nav_profile: 'Profile',
        save_alerts: 'SAVE PREFERENCES', alerts_title: 'Alert Settings',
        select_language: 'SELECT LANGUAGE', alert_monitoring_categories: '1. Monitoring Categories',
        apply_btn: 'APPLY NOW', budget: 'BUDGET', discuss: 'To discuss',
        reveal_info: 'INFORMATION REVEALED', open_wa: 'OPEN WHATSAPP', open_tg: 'OPEN TELEGRAM',
        profile_saved: 'PROFILE SAVED! ✨', apply_sent: 'APPLICATION SENT! ✨',
        fill_profile: 'Complete your profile before applying.',
        wa_confirm: 'Application sent! Do you want to contact via WhatsApp now?',
        acc_suspended: 'ACCOUNT SUSPENDED.',
        no_contact: 'THIS AD HAS NO PUBLIC CONTACT INFO.',
        saving: 'SAVING...', save_profile: 'SAVE ELITE PROFILE',
        applying: 'APPLYING...', retry: 'RETRY',
        tv: 'TV', tax: 'TAX', airbnb: 'AIRBNB', discount: 'DISCOUNT',
        // Landing
        verifying_session: 'VERIFYING SESSION',
        hero_badge: 'AI FILTERED FEED LIVE',
        hero_title: 'The World\'s Premium<br><span class="gold-text italic">Intelligence Feed</span>',
        hero_subtitle: 'Exclusive real-time listings from Telegram & WhatsApp, filtered specifically for VIP members.',
        launch_app: 'OPEN APP',
        account_access: 'ACCOUNT ACCESS',
        stat_cities: 'CITIES',
        stat_latency: 'LATENCY'
    },
    ru: {
        cat_plazas: 'ВАКАНСИИ', cat_eventos: 'СОБЫТИЯ',
        loading: 'Загрузка предложений...', no_offers: 'Предложений нет.',
        search_placeholder: 'Поиск агентств, моделей...', contact_btn: 'КОНТАКТ',
        logout: 'ВЫЙТИ',
        nav_home: 'Главная', nav_feed: 'Ленты', nav_alerts: 'Уведомления', nav_profile: 'Профиль',
        save_alerts: 'СОХРАНИТЬ', alerts_title: 'Настройки уведомлений',
        select_language: 'ВЫБРАТЬ ЯЗЫК', alert_monitoring_categories: '1. Категории мониторинга',
        apply_btn: 'ОТКЛИКНУТЬСЯ', budget: 'БЮДЖЕТ', discuss: 'По договоренности',
        reveal_info: 'ИНФОРМАЦИЯ ОТКРЫТА', open_wa: 'ОТКРЫТЬ WHATSAPP', open_tg: 'ОТКРЫТЬ TELEGRAM',
        profile_saved: 'ПРОФИЛЬ СОХРАНЕН! ✨', apply_sent: 'ОТКЛИК ОТПРАВЛЕН! ✨',
        fill_profile: 'Заполните профиль перед подачей заявки.',
        wa_confirm: 'Отклик отправлен! Хотите связаться через WhatsApp сейчас?',
        acc_suspended: 'АККАУНТ ЗАБЛОКИРОВАН.',
        no_contact: 'КОНТАКТНАЯ ИНФОРМАЦИЯ ОТСУТСТВУЕТ.',
        saving: 'СОХРАНЕНИЕ...', save_profile: 'СОХРАНИТЬ ПРОФИЛЬ',
        applying: 'ОТПРАВКА...', retry: 'ПОВТОРИТЬ',
        tv: 'ТВ', tax: 'НАЛОГ', airbnb: 'AIRBNB', discount: 'СКИДКА',
        // Landing
        verifying_session: 'ПРОВЕРКА СЕССИИ',
        hero_badge: 'AI ФИЛЬТРАЦИЯ В РЕАЛЬНОМ ВРЕМЕНИ',
        hero_title: 'Мировая Сеть<br><span class="gold-text italic">VIP Аналитики</span>',
        hero_subtitle: 'Эксклюзивные предложения из Telegram и WhatsApp в реальном времени, отфильтрованные для участников Elite.',
        launch_app: 'ОТКРЫТЬ APP',
        account_access: 'ВХОД В АККАУНТ',
        stat_cities: 'ГОРОДА',
        stat_latency: 'ЗАДЕРЖКА'
    },
    pt: {
        all: 'TUDO', cat_plazas: 'VAGAS', cat_eventos: 'EVENTOS',
        escorts: 'ESCORTS',
        loading: 'Carregando ofertas...', no_offers: 'Nenhuma oferta disponible.',
        search_placeholder: 'Buscar agências, modelos...', contact_btn: 'VER CONTATO',
        logout: 'SAIR',
        nav_home: 'Início', nav_feed: 'Feed', nav_alerts: 'Alertas', nav_profile: 'Perfil',
        save_alerts: 'SALVAR PREFERÊNCIAS', alerts_title: 'Configurar Alertas',
        select_language: 'SELECIONAR IDIOMA', alert_monitoring_categories: '1. Categorias de Monitoramento',
        apply_btn: 'CANDIDATAR-SE', budget: 'ORÇAMENTO', discuss: 'A combinar',
        reveal_info: 'INFORMAÇÃO REVELADA', open_wa: 'ABRIR WHATSAPP', open_tg: 'ABRIR TELEGRAM',
        profile_saved: 'PERFIL SALVO! ✨', apply_sent: 'CANDIDATURA ENVIADA! ✨',
        fill_profile: 'Complete seu perfil antes de se candidatar.',
        wa_confirm: 'Candidatura enviada! Quer entrar em contato pelo WhatsApp ahora?',
        acc_suspended: 'CONTA SUSPENSA.',
        no_contact: 'ESTE ANÚNCIO NÃO POSSUI CONTATO PÚBLICO.',
        saving: 'SALVANDO...', save_profile: 'SALVAR PERFIL ELITE',
        applying: 'ENVIANDO...', retry: 'TENTAR NOVAMENTE',
        tv: 'TV', tax: 'IMPOSTO', airbnb: 'AIRBNB', discount: 'DESCONTO',
        // Landing
        verifying_session: 'VERIFICANDO SESSÃO',
        hero_badge: 'FEED FILTRADO POR IA AO VIVO',
        hero_title: 'A Rede Global de<br><span class="gold-text italic">Inteligência VIP</span>',
        hero_subtitle: 'Anúncios exclusivos em tempo real do Telegram e WhatsApp, filtrados com precisão para membros VIP.',
        launch_app: 'ABRIR APP',
        account_access: 'ACESSO CONTA',
        stat_cities: 'CIDADES',
        stat_latency: 'LATÊNCIA'
    }
};
